config/routes.rb
Rails.application.routes.draw do
  resources :departamentos
  root 'produtos#index'
  resource :produtos, only: [:new, :create, :destroy]
  get 'produtos/busca' => 'produtos#busca', as: :busca_produto
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord

  validates :quantidade, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]

  # GET /departamentos
  # GET /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to @departamento, notice: 'Departamento was successfully created.' }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1
  # PATCH/PUT /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to @departamento, notice: 'Departamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento.destroy
    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: 'Departamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def departamento_params
      params.require(:departamento).permit(:nome)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  def index
    @produtos_por_nome = Produto.order(:nome).limit 5
    @produtos_por_preco = Produto.order(:preco).limit 2
  end

  def new
    @produto = Produto.new
  end

  def busca
    @nome_a_buscar = params[:nome]

    @produtos = Produto.where "nome like ?", "%#{@nome_a_buscar}%"
  end

  def create
    valores =params.require(:produto).permit :nome, :descricao, :preco, :quantidade
    @produto = Produto.new valores

    if @produto.save
      redirect_to root_url
    else
      render :new
    end
  end

  def destroy
    id = params[:id]

    Produto.destroy id

    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/departamentos/_form.html.erb
<%= form_with(model: departamento, local: true) do |form| %>
  <% if departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
      <% departamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Show', @departamento %> |
<%= link_to 'Back', departamentos_path %>

app/views/departamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departamentos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.nome %></td>
        <td><%= link_to 'Show', departamento %></td>
        <td><%= link_to 'Edit', edit_departamento_path(departamento) %></td>
        <td><%= link_to 'Destroy', departamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Departamento', new_departamento_path %>

app/views/departamentos/new.html.erb
<h1>New Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Back', departamentos_path %>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @departamento.nome %>
</p>

<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lojadecamisetas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="<%= root_url %>">Loja de Camisetas</a>
      <%= form_tag busca_produto_path, method: :get, class: 'navbar-form navbar-right' do %>
        <div class="input-group">
          <%= text_field_tag :nome, @nome_a_buscar, class: 'form-control' %>
          <%= button_to "Buscar", nil, class: 'btn btn-primary' %>
        </div>
    <% end %>
    </nav>

    <section class="container">

      <%= yield %>

    </section>

  </body>
</html>

app/views/produtos/_produto.html.erb
<tr>
  <td><%= produto.nome %></td>
  <td><%= produto.descricao %></td>
  <td><%=produto.preco %></td>
  <td><%= produto.quantidade %></td>
  <td><%= button_to "Remover", produtos_path, method: :delete, class: "btn btn-danger", data: {confirm: "Tem certeza que deseja remover o produto #{produto.nome}?"} %></td>
</tr>

app/views/produtos/busca.html.erb
<div class="row">
  <div class="col-sm-6">
    <table>
      <h2>Resultado da Busca</h2>
      <thead class="table table-hover">
      <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Preço</th>
        <th>Quantidade</th>
      </tr>
      </thead>
      <tbody>
        <%= render @produtos %>
      </tbody>
    </table>
  </div>

</div>

<%= link_to 'Cadastrar Produto', new_produtos_path, class: 'btn btn-success mt-5' %>

app/views/produtos/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <table>
      <h2>Ordenado por Nome</h2>
      <thead class="table table-hover">
      <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Preço</th>
        <th>Quantidade</th>
      </tr>
      </thead>
      <tbody>
        <%= render @produtos_por_nome %>
      </tbody>
    </table>
  </div>
  <div class="col-sm-6">
    <table>
      <h2>Ordenado por Preço</h2>
      <thead class="table table-hover">
      <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Preço</th>
        <th>Quantidade</th>
      </tr>
      </thead>
      <tbody>
        <%= render @produtos_por_preco %>
      </tbody>
    </table>
  </div>

</div>

<%= link_to 'Cadastrar Produto', new_produtos_path, class: 'btn btn-success mt-5' %>

app/views/produtos/new.html.erb
<% @produto.errors.full_messages.each do |message| %>
  <div class="alert alert-danger" role="alert">
    <%= message %>
  </div>
<% end %>

<div class="row">

  <div class="col-sm-6">

    <%= form_for @produto do |f| %>

      <div class="form-group">
        <%= f.label :nome %>
        <%= f.text_field :nome, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :descricao %>
        <%= f.text_area :descricao, class: "form-control", rows: 5 %>
      </div>

      <div class="form-group">
        <%= f.label :quantidade %>
        <%= f.number_field :quantidade, step: 1, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :preco %>
        <%= f.number_field :preco, class: "form-control" %>
      </div>

      <%= f.submit 'Criar o produto', class: "btn btn-primary mt-4" %>
  <% end %>

  </div>

</div>